name: Debian

images:
  debian:
    target: debian
    edge: true
    alias:
      - latest
      - $(VERSION)
      - $(VERSION)-debian
    tests:
      - dolt
      - git-dolt
      - curl
      - wget

tests:
  dolt:
    command: version
    expected: dolt version

  git-dolt:
    entrypoint: git-dolt

  curl:
    entrypoint: curl
    command: --version

  make:
    entrypoint: make
    command: --version

  wget:
    entrypoint: wget
    command: --version