name: Debian

images:
  debian:
    target: debian
    edge: true
    alias:
      - latest
      - $(VERSION)
      - $(VERSION)-debian
    tests:
      - dolt
      - git-dolt

tests:
  dolt:
    command: version
    expected: dolt version

  git-dolt:
    entrypoint: git-dolt