name: Docker build

on:
  push:
    branches:
      - master
  release:
    types:
      - released

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: latest

    - name: Prepare
      run: make prepare

    - name: Build
      run: make build

    - name: Docker login
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Push egde images
      if: "!startsWith(github.ref, 'refs/tags/')"
      run: make push-edge

    - name: Push stable images
      if: "startsWith(github.ref, 'refs/tags/')"
      run: make push-stable
